// Copyright 2026 kropath Authors.
// SPDX-License-Identifier: Apache-2.0

// gen-monitoring writes config/monitoring/prometheusrule.yaml from the canonical
// config/monitoring/rules.yaml. rules.yaml is the source of truth — it is what
// `promtool check rules` validates directly — and prometheusrule.yaml is the
// Prometheus Operator PrometheusRule CR generated from it (spec §4, design §10.2).
//
// Usage:
//
//	go run ./cmd/gen-monitoring           # regenerate config/monitoring/prometheusrule.yaml
//	go run ./cmd/gen-monitoring --check   # exit non-zero if the file is stale
//
// Run via `make monitoring-gen` or `make monitoring-verify`.
// Must be run from the repository root.
package main

import (
	"bytes"
	"fmt"
	"io"
	"os"

	"gopkg.in/yaml.v3"

	"github.com/kropath/kropath-controller/internal/monitoring"
)

const (
	rulesPath = "config/monitoring/rules.yaml"
	outPath   = "config/monitoring/prometheusrule.yaml"
	ruleName  = "kropath-controller"
)

// prometheusRule is the minimal PrometheusRule CR shape this generator emits:
// metadata.name and metadata.labels pinned per spec §4, spec.groups copied
// verbatim from rules.yaml.
type prometheusRule struct {
	APIVersion string                 `yaml:"apiVersion"`
	Kind       string                 `yaml:"kind"`
	Metadata   prometheusRuleMetadata `yaml:"metadata"`
	Spec       prometheusRuleSpec     `yaml:"spec"`
}

type prometheusRuleMetadata struct {
	Name   string            `yaml:"name"`
	Labels map[string]string `yaml:"labels"`
}

type prometheusRuleSpec struct {
	Groups []monitoring.RuleGroup `yaml:"groups"`
}

// generate marshals the PrometheusRule CR built from groups and writes the
// result (with header) to w.
func generate(w io.Writer, groups []monitoring.RuleGroup) error {
	cr := prometheusRule{
		APIVersion: "monitoring.coreos.com/v1",
		Kind:       "PrometheusRule",
		Metadata: prometheusRuleMetadata{
			Name: ruleName,
			Labels: map[string]string{
				"app.kubernetes.io/name": ruleName,
			},
		},
		Spec: prometheusRuleSpec{Groups: groups},
	}

	doc, err := yaml.Marshal(cr)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if _, err := fmt.Fprintln(w, "# Auto-generated by cmd/gen-monitoring from config/monitoring/rules.yaml — do NOT edit by hand."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "# Regenerate with: make monitoring-gen"); err != nil {
		return err
	}
	_, err = w.Write(doc)
	return err
}

func main() {
	checkMode := len(os.Args) > 1 && os.Args[1] == "--check"

	rf, err := monitoring.LoadRulesFile(rulesPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "gen-monitoring: %v\n", err)
		os.Exit(1)
	}

	var buf bytes.Buffer
	if err := generate(&buf, rf.Groups); err != nil {
		fmt.Fprintf(os.Stderr, "gen-monitoring: %v\n", err)
		os.Exit(1)
	}

	if checkMode {
		existing, err := os.ReadFile(outPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "monitoring-verify: cannot read %s: %v\n", outPath, err)
			os.Exit(1)
		}
		if !bytes.Equal(existing, buf.Bytes()) {
			fmt.Fprintf(os.Stderr, "monitoring-verify: %s is stale — run: make monitoring-gen\n", outPath)
			os.Exit(1)
		}
		fmt.Fprintf(os.Stderr, "monitoring-verify: %s is up to date\n", outPath)
		return
	}

	if err := os.WriteFile(outPath, buf.Bytes(), 0o644); err != nil { // #nosec G306 -- config/monitoring/prometheusrule.yaml is a world-readable checked-in manifest
		fmt.Fprintf(os.Stderr, "gen-monitoring: %v\n", err)
		os.Exit(1)
	}
	fmt.Fprintf(os.Stderr, "gen-monitoring: wrote %s (%d groups)\n", outPath, len(rf.Groups))
}
