// Copyright 2026 kropath Authors.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"bytes"
	"strings"
	"testing"

	"github.com/kropath/kropath-aws-controller/internal/monitoring"
)

func sampleGroups() []monitoring.RuleGroup {
	return []monitoring.RuleGroup{
		{
			Name: "kropath-aws-controller.governance",
			Rules: []monitoring.Rule{
				{
					Alert: "KropathConfigUnreferenced",
					Expr:  `max (kropath_kropathconfigstatus_configs{reason="Unreferenced"}) > 0`,
					For:   "10m",
					Labels: monitoring.RuleLabels{
						Severity:  "critical",
						Component: "kropath-aws-controller",
					},
					Annotations: monitoring.RuleAnnotations{
						Summary: "A KropathConfig is resolved by no <Family>Config.",
					},
				},
			},
		},
	}
}

// TestGenerate_header verifies the required "do not edit" header and
// regeneration instruction are present.
func TestGenerate_header(t *testing.T) {
	var buf bytes.Buffer
	if err := generate(&buf, sampleGroups()); err != nil {
		t.Fatalf("generate: %v", err)
	}
	out := buf.String()
	if !strings.HasPrefix(out, "# Auto-generated by cmd/gen-monitoring") {
		t.Errorf("missing 'do not edit' header: %q", out)
	}
	if !strings.Contains(out, "# Regenerate with: make monitoring-gen") {
		t.Errorf("missing 'make monitoring-gen' instruction: %q", out)
	}
}

// TestGenerate_pinnedMetadata verifies the CR envelope fields spec §4 pins:
// apiVersion, kind, metadata.name, and metadata.labels.
func TestGenerate_pinnedMetadata(t *testing.T) {
	var buf bytes.Buffer
	if err := generate(&buf, sampleGroups()); err != nil {
		t.Fatalf("generate: %v", err)
	}
	out := buf.String()

	for _, want := range []string{
		"apiVersion: monitoring.coreos.com/v1",
		"kind: PrometheusRule",
		"name: kropath-aws-controller",
		"app.kubernetes.io/name: kropath-aws-controller",
		"name: kropath-aws-controller.governance",
		"alert: KropathConfigUnreferenced",
	} {
		if !strings.Contains(out, want) {
			t.Errorf("output missing %q:\n%s", want, out)
		}
	}
}

// TestGenerate_deterministic verifies that calling generate twice with the
// same input produces byte-identical output, which is what the drift gate
// (monitoring-verify) depends on.
func TestGenerate_deterministic(t *testing.T) {
	groups := sampleGroups()

	var first, second bytes.Buffer
	if err := generate(&first, groups); err != nil {
		t.Fatalf("first generate: %v", err)
	}
	if err := generate(&second, groups); err != nil {
		t.Fatalf("second generate: %v", err)
	}
	if !bytes.Equal(first.Bytes(), second.Bytes()) {
		t.Error("generate is not deterministic: two calls with the same input produced different output")
	}
}

// TestGenerate_emptyGroups verifies an empty group list still produces a
// valid, parseable document rather than an error.
func TestGenerate_emptyGroups(t *testing.T) {
	var buf bytes.Buffer
	if err := generate(&buf, nil); err != nil {
		t.Fatalf("generate(nil): %v", err)
	}
	if !strings.Contains(buf.String(), "spec:") {
		t.Errorf("expected a spec: key even with no groups, got:\n%s", buf.String())
	}
}
